version: "2"
services: 
    client:
        build: ./client
        ports: 
            - "4600:80"
    server:
        build: ./server
        user: node
        working_dir: /home/node/app
        environment:
          - NODE_ENV=production
        volumes:
          - ./server/dist:/home/node/app
        command: "npm run run"