version: "2"
services: 
    client:
        build: ./client
        ports: 
            - "4500:80"
    server:
        build: ./server
        user: node
        working_dir: /home/node/app
        environment:
          - NODE_ENV=production
          - SESSION_SECRET=348907y34h98347yh93487h3
          - PORT=4500             
        volumes:
          - ./server:/home/node/app
        command: "npm run run"